### ISSUE TITLE
make a partial to process scss files and render <link> tags 

### ISSUE THREAD

**Issue by davidstanke** [dora-team/dora.dev#121]
```
    <!-- TODO: make a partial to process scss files and render <link> tags -->
```

(see e.g. /layouts/quickcheck/results.html ... this pattern is repeated, in e.g. /partials/head.html)

**Comment by davidstanke** [comment]
Hey @jessegduke would you be interested in taking this on? It's been nagging at me for a while, and it seems like a great way to leverage our new "proper" theme: we can DRY it out in the templates and use a partial provided by the theme. WDYT?

**Comment by jessegduke** [comment]
Will check it out.

**Comment by jessegduke** [comment]
@davidstanke As the Hugo expert, can you take a quick peer review of the following and see if this is in alignment with your thoughts.

```
modified:   hugo/layouts/quickcheck/results.html (line 4)
modified:   hugo/themes/dora/layouts/partials/head.html (lines 19, 23-25)
new file:   hugo/themes/dora/layouts/partials/link_styles.html (new partial)
```

I saw (at least two patterns).  One with Options and one without.  I am not sure if they covers all of them, but maybe this will work?  Maybe we can drop the Options, but I was not sure your approach.

Let me know your thoughts, please.

**Comment by jessegduke** [comment]
Update:  I think I can make the `options` variable in the partial as a pseudo optional with defaults of empty.  Doing that would simplify the parent and remove the need to pass in an empty var into the partial.

If you are ok with the general approach, I will move to make the `options` as "optional" for the parent html.

**Comment by jessegduke** [comment]
Re "Options", got it; Thanks.  What I would propose is that we move the intelligence to support Options in the partial, so that if someone in another implementation wanted/needed to use the css output they could -- but retain the simplifies experience for the calling Template.

Re: the second point, let me do some research.  Some of the goals, I think I met in latest push. However, I want to better understand your larger references on the  `resources.Get` and "page bundles"

Thanks!
