### ISSUE TITLE
SEM diagrams in /research/ section

### ISSUE THREAD

**Issue by steve-fenton-octopus** [dora-team/dora.dev#145]
I'm loving the new site and can't wait for the green light to start updating all my backlinks to point to it.

The /research/ section has different versions of the SEM/BFD, but I had the following questions in my head as I clicked through that maybe the site could answer as others may also have questions.

**Explore DORA’s Research Program**
https://dora.dev/research/

The 2020 SEM is shown on the landing page. It left me wondering why this was shown rather than the most recent one.

**DORA’s Research Program: 2020**
https://dora.dev/research/archives/2020/

Interestingly, the 2020 SEM isn't shown on this page. I wondered if it should be shown, even though a full report wasn't done in 2020.

There may be good reasons for both of these, but I wondered if a sentence that explained the reason might help?

**Comment by davidstanke** [comment]
Whoa! This is old now. Now that we have Core, we have a clearer response to these concerns. That doesn't resolve the question of "why don't we have the 2020 'SEM' on the 2020 page?" But, now that we have Core, I'm kind of uncomfortable putting it on there. Because it's not really a SEM [a cohesive model from a single research study], it's really an abstraction across multiple years of study -- ie. it's a proto-Core. Given that, I'm inclined to not put it on the research page.

**Comment by steve-fenton-octopus** [comment]
I'm happy with this - DORA Core feels like the best way to get into the model for folks landing on the webiste.
