### ISSUE TITLE
Dora.dev - Link to The Accelerate State of DevOps Report 2023 is broken

### ISSUE THREAD

**Issue by phalamaj-sendati** [dora-team/dora.dev#440]
Hello team , when you browse dora.dev and try to access the "The Accelerate State of DevOps Report 2023" 
 is giving me an 503 error ( service unavailable ) and the link is pointing to https://cloud.google.com/devops/state-of-devops

My setup is:

- Distributor ID:	Ubuntu
- Description:	Ubuntu 22.04.3 LTS
- Release:	22.04
- Codename:	jammy
- Browser: Chrome Version 118.0.5993.88 (Official Build) (64-bit)

Best.

**Comment by davidstanke** [comment]
Hi @phalamaj-sendati, I have tried to replicate this and I've been unable (I have access to an Ubuntu 20.x machine, but not a 22.x machine, though I think it's unlikely that would make a difference).

Can you think of anything else on your end that might affect the connection? For example, might there be network restrictions blocking access to some resources on the site? Note that the report is served from a different site (cloud.google.com) than dora.dev.

**Comment by phalamaj-sendati** [comment]
Hello @davidstanke,

You can check that the  link is in the web using curl

~~~
$ curl -s "https://dora.dev/" | grep "The Accelerate State of DevOps Report 2023"
    The Accelerate State of DevOps Report 2023 is now available! <a href="https://cloud.google.com/devops/state-of-devops" target="_blank">Download the 2023 DORA Report</a>
    <h2><a href='https://cloud.google.com/devops/state-of-devops' target="_blank">The Accelerate State of DevOps Report 2023</a></h2>
            <a href='https://cloud.google.com/devops/state-of-devops' target="_blank"><img src='/research/2023/dora-report/2023-dora-accelerate-state-of-devops-report.png' alt='The Accelerate State of DevOps Report 2023' class='feature  stroke'></a>
$ 
~~~

In other test i found that the link 'https://cloud.google.com/devops/state-of-devops' some times work and render a form to access the report and sometimes fails.
So it's not a dora's web page problem perse but more a problem in your provider ( cloud.google.com )

Hope this info helps.

**Comment by davidstanke** [comment]
Yes, it sounds like you're having trouble accessing a page on cloud.google.com -- you mention that sometimes it works, and sometimes it fails. Have you seen any patterns in that? Are you sending different requests for the failures and successes, or is it intermittently failing with the same request each time? What happens if you request it directly from a terminal, ie. `curl https://cloud.google.com/devops/state-of-devops`? What language is your browser set to, and do you have any extensions that might modify the request?

Thanks for helping us to understand your experience—we'd like to fix it! But we haven't been able to replicate the problem so I'm trying to understand what's unique about your situation.

**Comment by phalamaj-sendati** [comment]
Hello @davidstanke , seems that the error is erratic, now most of the time the web page loads good.
My browser is set to English and my extensions are "decentraleyes" and "privacy badger".

As the page now render most of the time ok, i think we can close this issue.

Best
