### ISSUE TITLE
Quickcheck:  rendering issues on the comparisons tabs

### ISSUE THREAD

**Issue by nathenharvey** [dora-team/dora.dev#475]
The comparison tabs don't render properly when first visiting them.  A refresh fixes the layout.

https://github.com/dora-team/dora.dev/assets/16093/35abb0e9-d508-4c68-98a3-3a0f671ca8ad

**Comment by davidstanke** [comment]
Yes. This is true. :) Thank you for reporting it; it's been nagging at me for a long time but the quick fixes I've tried haven't worked, and I've neglected to log an issue because I feel frustrated—bad behavior by me. I think it's time to reimplement those (they're the last bit still using d3, which is flexible but fragile).

**Comment by davidstanke** [comment]
Now that we've reimplemented the quick check, this only occurs on the legacy versions, and I'm inclined to let it lie.
